#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pangox-compat
Version  : 0.0.2
Release  : 1
URL      : https://github.com/GNOME/pangox-compat/archive/0.0.2.tar.gz
Source0  : https://github.com/GNOME/pangox-compat/archive/0.0.2.tar.gz
Summary  : X Window System font support for Pango
Group    : Development/Tools
License  : LGPL-2.0
Requires: pangox-compat-lib = %{version}-%{release}
Requires: pangox-compat-license = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(pango)

%description
This is a compatibility library providing the obsolete pangox library
that is not shipped by Pango itself anymore.  If you are still using
pangox, well, really, get a life...

%package dev
Summary: dev components for the pangox-compat package.
Group: Development
Requires: pangox-compat-lib = %{version}-%{release}
Provides: pangox-compat-devel = %{version}-%{release}

%description dev
dev components for the pangox-compat package.


%package lib
Summary: lib components for the pangox-compat package.
Group: Libraries
Requires: pangox-compat-license = %{version}-%{release}

%description lib
lib components for the pangox-compat package.


%package license
Summary: license components for the pangox-compat package.
Group: Default

%description license
license components for the pangox-compat package.


%prep
%setup -q -n pangox-compat-0.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543731590
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1543731590
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pangox-compat
cp COPYING %{buildroot}/usr/share/package-licenses/pangox-compat/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pango-1.0/pango/pangox.h
/usr/lib64/libpangox-1.0.so
/usr/lib64/pkgconfig/pangox.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpangox-1.0.so.0
/usr/lib64/libpangox-1.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pangox-compat/COPYING
